name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Bump release version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.1.0
      with:
        current-version: '2.0.0'
        version-fragment: 'feature'
        
    - name: Docker Build and Push
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          tags: swapnilsahare/my-app:${{ steps.get_version.outputs.new_version }}

  deploy:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     - name: Docker Build & Push Action
       uses: mr-smithers-excellent/docker-build-push@v6.2
       with:
        image: swapnilsahare/my-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
        
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Linter and Test
      run: ./gradlew check
    - name: Upload Reports
      uses: actions/upload-artifact@v2
      with:
        name: Test-Reports
        path: app/build/reports
      if: always()
